# Generated by Django 5.1.7 on 2025-03-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('idade', models.IntegerField()),
                ('cpf', models.CharField(max_length=11)),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('idade', models.IntegerField()),
                ('cpf', models.CharField(max_length=11)),
                ('especialidade', models.CharField(max_length=100)),
                ('cref', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Personal Trainer',
                'verbose_name_plural': 'Personais Trainers',
            },
        ),
    ]
